# This file can be used to customize the files managed by PDK.
#
# See https://github.com/danielparks/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/danielparks/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.github/workflows/pr-checks.yaml:
  additional-platforms:
    - macos-latest
